# This is a basic workflow to help you get started with Actions

name: Darth Vader Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setvaderline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      darthvaderquote: ${{steps.set-quote.outputs.darthvaderquote }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Set Darth Vader Quote
       id: set-quote
       run: echo "darthvaderquote="I find your lack of faith disturbing" >> $VADER_OUTPUT
  echovaderline:
    needs: setvaderline
    runs-on: ubuntu-latest
    steps: 
     - name: Read/Echo output from setvaderline
       env:
        VADER_OUTPUT: ${{needs.setvaderline.outputs.darthvaderquote}}
       run: echo "VADER_OUTPUT"
