# This is a basic workflow to help you get started with Actions

name: Darth Vader Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setvaderline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      darthvaderquote: ${{steps.step1.outputs.text}}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     -name: Set Darth Vader quote "I find your lack of faith disturbing" as output and not echoing
     id: set-output
     run: echo "darthvaderquote="I find your lack of faith disturbing" >> $GITHUB_OUTPUT

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
