# name: Workflow Initiated by - gap931
# on:
#   workflow_dispatch:

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   my_first_job:
#     name: My First Job
#     runs-on: ubuntu-latest
#     outputs:
#       output1: ${{ steps.step1.outputs.output1 }}
#       output2: ${{ steps.step2.outputs.output2 }}
#     steps:
#     - id: step1
#       run: echo "test=hello" >> $GITHUB_OUTPUT
#     - id: step2
#       run: echo "test=world" >> $GITHUB_OUTPUT


#   my_second_job:
#       name: My Second Job
#       runs-on: ubuntu-latest
#       needs: my_first_job # This job will only run if the first job is successful
#       steps:
#       - env:
#             output1: ${{ needs.my_first_job.outputs.output1 }}
#             output2: ${{ needs.my_first_job.outputs.output2 }}
#         run: "$output1 $output2"


# This is a basic workflow to help you get started with Actions

name: Darth Vader Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
  inputs:
    environment:
      description: "Choose Env"
        required: true
        default: "dev"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setvaderline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      darthvaderquote: ${{steps.set-quote.outputs.darthvaderquote }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Set Darth Vader Quote
       id: set-quote
       run: echo darthvaderquote="I find your lack of faith disturbing" >> $"VADER_OUTPUT"
  echovaderline:
    needs: setvaderline
    runs-on: ubuntu-latest
    steps: 
     - name: Read/Echo output from setvaderline
       env:
        VADER_OUTPUT: ${{needs.setvaderline.outputs.darthvaderquote}}
       run: echo "VADER_OUTPUT"