name: Workflow Initiated by - gap931
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  my_first_job:
    name: My First Job
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
      output2: ${{ steps.step2.outputs.output2 }}
    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT


  my_second_job:
      name: My Second Job
      runs-on: ubuntu-latest
      needs: my_first_job # This job will only run if the first job is successful
      steps:
      - env:
            output1: ${{ needs.my_first_job.outputs.output1 }}
            output2: ${{ needs.my_first_job.outputs.output2 }}
        run: "$output1 $output2"