#This is a basic workflow to help you get started with Actions

name: Darth Vader Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setvaderline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      darthvaderquote: ${{steps.set-quote.outputs.darthvaderquote }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Set Darth Vader Quote
       id: set-quote
       run: echo "darthvaderquote= I find your lack of faith disturbing" >> $GITHUB_OUTPUT
       env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_VAR: ${{ vars.MY_VAR }}
  echovaderline:
    needs: setvaderline
    environment: dev
    runs-on: ubuntu-latest
    steps: 
       #env:
    - run: |
        darthvaderquote="${{ needs.setvaderline.outputs.darthvaderquote }}"
        echo "Darth Vader Quote: $darthvaderquote"
      env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_VAR: ${{ vars.MY_VAR }}